export const AUDIT_ACTION_CONFIGS: Record<string, { label: string, color: string }> = {
    'create': { label: 'Criação', color: 'bg-green-100 text-green-700 font-black' },
    'update': { label: 'Edição', color: 'bg-blue-100 text-blue-700 font-black' },
    'update_status': { label: 'Status', color: 'bg-amber-100 text-amber-700 font-black' },
    'delete': { label: 'Exclusão', color: 'bg-red-100 text-red-700 font-black' },
    'login': { label: 'Login', color: 'bg-purple-100 text-purple-700 font-black' },
    'upload_document': { label: 'Documento', color: 'bg-indigo-100 text-indigo-700 font-black' },
    'delete_document': { label: 'Exclusão Doc', color: 'bg-rose-100 text-rose-700 font-black' },
    'update_permission': { label: 'Permissão', color: 'bg-cyan-100 text-cyan-700 font-black' },
    'create_role': { label: 'Novo Cargo', color: 'bg-teal-100 text-teal-700 font-black' },
    'delete_role': { label: 'Exclusão Cargo', color: 'bg-pink-100 text-pink-700 font-black' },
    'invite_user': { label: 'Convite', color: 'bg-emerald-100 text-emerald-700 font-black' },
    'update_user_role': { label: 'Cargo Usuário', color: 'bg-orange-100 text-orange-700 font-black' },
    'export_data': { label: 'Exportação', color: 'bg-slate-100 text-slate-700 font-black' },
    'billing_checkout': { label: 'Checkout', color: 'bg-sky-100 text-sky-700 font-black' },
    'billing_portal': { label: 'Portal', color: 'bg-indigo-100 text-indigo-700 font-black' },
    'update_subscription': { label: 'Assinatura', color: 'bg-violet-100 text-violet-700 font-black' },
    'cancel_subscription': { label: 'Cancelamento', color: 'bg-rose-100 text-rose-700 font-black' },
} as const
